name = "linh-profile"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "Personal portfolio website of Nguyen Mai Xuan Linh â€“ Business Analyst | Data Analyst | QA Tester"
homepage = "https://github.com/gurusabarish/hugo-profile"
demosite = "https://hugo-profile.netlify.app"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "Nguyen Mai Xuan Linh"
  homepage = "https://github.com/sunshinebabyz"

